UrbanDelivery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from accounts.views import signup_view, activation_sent_view, activate, post_detail_view, signup
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from accounts import forms
from django.contrib.auth.views import LoginView
from . import views, settings

from django_otp.admin import OTPAdminSite
class OTPAdmin(OTPAdminSite):
    pass

from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)
admin.site.site_header = "URBAN DELIVERY"
admin.site.site_title = "URBAN DELIVERY ADMIN PORTAL"
admin.site.index_title = "WELCOME TO URBAN DELIVERY ADMIN PORTAL"


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/', views.user_login, name='admin'),
    #path('posts/', views.post_detail_view.as_view()),
    url(r'',include('accounts.urls')),
    #url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^$',views.delivery_person_view, name='home'),
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^signup/$', signup, name="signup"),
    url(r'^thanks/$', views.HomePage.as_view(), name='thanks'),
    url(r'^admin_site/$',views.AdminPage.as_view(), name='adminpage'),
    url(r'validate/$', views.Validateuser, name='validate_login'),
    url(r'^$', views.ValidateOTP, name='validate_otp'),
    url(r'^saved/', views.HomePage.as_view(), name ='saved'),
    url(r'^employee/$',views.Employee, name='delivery'),
    url(r'^download/$',views.download, name='download'),
    path('accounts/login/', LoginView.as_view(authentication_form=forms.OTPAuthenticationForm), name="login"),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^$', views.index),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from accounts import views
from .views import signup_view, activation_sent_view, activate
from django.contrib.auth import views as auth_views
from django.urls import re_path
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
   url(r'^about/$',views.AboutView.as_view(),name='about'),
   url(r'^contact/$',views.DetailView.as_view(),name='contact'),
   url(r'login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
   url(r'EmployeeLogin/$', auth_views.LoginView.as_view(template_name='blog/employee.html'), name='delivery'),
   url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
   re_path(r'^totp/create/$', views.TOTPCreateView.as_view(), name='totp-create'),
   re_path(r'^totp/login/(?P<token>[0-9]{6})/$', views.TOTPVerifyView.as_view(), name='totp-login'),
   path('post/new/', views.post_new, name='post_new'),
   url(r'^posts/', views.post_detail_view, name='post_list'),
   url(r'^profile/',views.SaveProfile, name='saveprofile'),
   url(r'^post/(?P<pk>\d+)$',views.PostDetailView,name='post_detail'),
   #path('', views.post_list, name='post_list'),
   #path('post/<int:pk>/', views.post_detail, name='post_detail'),
   url(r'post/new/amount',views.calculate_amount_view, name='calculate_amount'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/employee.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <div class="form">
    <form method="POST">
      {% csrf_token %}
      <table class="table">
                    <br>
                    <tr>
                        <td><h2 >Delivery Person Portal</h2></td>
                       <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:saveprofile' %}';">CLICK TO BE A DELIVERY PERSON</button></td>  
                    </tr>
                    <tr>
                        <td><label for="id_username">USERNAME</label></td>
                        <td><input id="id_username" name="username"
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">PASSWORD</label></td>
                        <td><input id="id_password" name="password"
                                   type="password" class="form-control"></td>
                    </tr>
                    <br>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}
      <button type="submit" class="button button-block" name='login'>Login</button>
    </form>
  </div>
</div>

{% endblock %}

templates/blog/newpost.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="form">
    <form  method="POST" class= 'profile' enctype="multipart/form-data">
      <h1 class='heading'>NEW PICKUP REQUEST</h1>
      <br>
      {% csrf_token %}
      {% for field in form %}
          <p>
            {{ field }}

            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
          <br>
      {% endfor %}
      <input type="submit" class="button button-block" value="Submit">
   </form>
  </div>
</div>
{% endblock %}

templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ amount }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/blog/postdetail.html
<!DOCTYPE html>
{% load static %}
 <html lang="en">
  <head>
   <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <meta name="description" content="">
      <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
     <meta name="generator" content="Jekyll v4.1.1">
         <title>{% block title %}URBAN DELIVERY{% endblock title %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
       <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
     <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
     <link rel="stylesheet" href="{% static 'mechit/css/master.css' %}">
     <link rel="stylesheet" href="{% static 'mechit/css/bootstrap.min.css' %}">
     <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
     <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
     <style>

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <nav class="site-header sticky-top py-1 bg-danger">
      <div class="container d-flex flex-column flex-md-row justify-content-between">

            <a class='navbar-brand' href='{% url 'home' %}'><img src="/static/mechit/images/URBAN DELIVERY.svg" width="30" height="30" alt=""> Welcome '{{user.username}}'</a>
            <table>
              <tr>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:post_list' %}';">CHECK REQUEST</button></td>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:logout' %}';">LOGOUT</button></td>
              </tr>
            </table>

      </div>

    </nav>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 bg-dark">

        <table class="rounded float-left text-white">
          <tr>
            <td><label for="">Name: </label></td>
            <td>{{ post.Name }}</td>
          </tr>
          <tr>
            <td><label for="">Address: </label></td>
            <td>{{ post.Address }}</td>
          </tr>
          <tr>
            <td><label for="">City: </label></td>
            <td>{{ post.City }}</td>
          </tr>
          <tr>
            <td><label for="">State: </label></td>
            <td>{{ post.State }}</td>
          </tr>
          <tr>
            <td><label for="">Pincode: </label></td>
            <td>{{ post.Pincode }}</td>
          </tr>
          <tr>
            <td><label for="">Mobile No. : </label></td>
            <td>{{ post.MobileNumber }}</td>
          </tr>
          <tr>
            <td><label for="">ShipmentWeight: </label></td>
            <td>{{ post.ShipmentWeight }}</td>
          </tr>
          <tr>
            <td><label for="">PickUp Location: </label></td>
            <td>{{ post.Origin }}</td>
          </tr>
          <tr>
            <td><label for="">Destination: </label></td>
            <td>{{ post.Destination }}</td>
          </tr>
          <tr>
            <td><label for="">Request Submittted on : </label></td>
            <td>{{ post.created_date }}</td>
          </tr>
          <tr>
            <td><label for="">Status of Request : </label></td>
            <td>{{ post.Status }}</td>
          </tr>
          <tr>
            <td><label for="">Request Assigned to : </label></td>
            <td>{{ post.deliveryperson }}</td>
          </tr>
          <tr>
            <td><label for="">Total Amount to be Paid :  </label></td>
            <td> {{ post.Totalamount }}</td>
          </tr>
        </table>

      <div class="rounded float-right">
        {% if post.Uploadimage %}
        <img src="{{ post.Uploadimage.url }}" alt="" width="500" height="500" padding-bottom:40px;>
        {% endif %}
      </div>
    </div>
</body>
</html>

templates/blog/postlist.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
 <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
   <meta name="generator" content="Jekyll v4.1.1">
      <title>{% block title %}URBAN DELIVERY{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <link rel="stylesheet" href="{% static 'mechit/css/master.css' %}">
    <link rel="stylesheet" href="{% static 'mechit/css/bootstrap.min.css' %}">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <nav class="site-header sticky-top py-1 bg-danger">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        {% if  DP %}
            <a class='navbar-brand' href='{% url 'home' %}'> <img src="/static/mechit/images/URBAN DELIVERY.svg" width="30" height="30" alt="">Welcome '{{user.username}}'</a>
            <a class='py-2 d-none d-md-inline-block' href="{% url 'accounts:post_new' %}">New Request</a>
            <a class='py-2 d-none d-md-inline-block' href="{% url 'accounts:post_list' %}">Requests</a>
            <table>
              <tr>
                <td><button type="button" class="btn btn-primary" onclick="location.href='{% url 'accounts:saveprofile' %}';">JOIN US</button></td>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:logout' %}';">LOGOUT</button></td>
              </tr>
            </table>
          {% else %}

            <a class='navbar-brand' href='{% url 'home' %}'><img src="/static/mechit/images/URBAN DELIVERY.svg" width="30" height="30" alt=""> Welcome '{{user.username}}'</a>
            <table>
              <tr>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:post_list' %}';">CHECK REQUEST</button></td>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:logout' %}';">LOGOUT</button></td>
              </tr>
            </table>

          {% endif %}
      </div>

    </nav>
    {% for post in posts %}
    <div class="form">
      <h3><a href="{% url 'accounts:post_detail' pk=post.pk %}"> Request id:{{ post.id }} submitted  on {{ post.created_date }}</a></h3>
    </div>
    {% endfor %}
</body>
</html>

templates/blog/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="form">
    <form  method="POST" class= 'profile' enctype="multipart/form-data">
      <h1 class='heading'>Delivery Person Registration Form</h1>
      <br>
      {% csrf_token %}
      {% for field in MyProfileForm %}
          <p>
            {{ field }}

            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
          <br>
      {% endfor %}
      <input type="submit" class="button button-block" value="Submit">
   </form>
  </div>
</div>
{% endblock %}

templates/blog/profilesaved.html
{% extends 'base.html' %}
{% block content %}
<html>
   <body>

      {% if saved %}
         <strong>Your profile was saved.</strong>
      {% endif %}

      {% if not saved %}
         <strong>Your profile was not saved.</strong>
      {% endif %}

   </body>
</html>

{% endblock %}