UrbanDelivery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from accounts.views import signup_view, activation_sent_view, activate, post_detail_view, signup
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from accounts import forms
from django.contrib.auth.views import LoginView
from . import views, settings

from django_otp.admin import OTPAdminSite
class OTPAdmin(OTPAdminSite):
    pass

from django.contrib.auth.models import User
from django_otp.plugins.otp_totp.models import TOTPDevice

admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice)
admin.site.site_header = "URBAN DELIVERY"
admin.site.site_title = "URBAN DELIVERY ADMIN PORTAL"
admin.site.index_title = "WELCOME TO URBAN DELIVERY ADMIN PORTAL"


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('admin/', views.user_login, name='admin'),
    #path('posts/', views.post_detail_view.as_view()),
    url(r'',include('accounts.urls')),
    #url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^$',views.delivery_person_view, name='home'),
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^signup/$', signup, name="signup"),
    url(r'^thanks/$', views.HomePage.as_view(), name='thanks'),
    url(r'^admin_site/$',views.AdminPage.as_view(), name='adminpage'),
    url(r'validate/$', views.Validateuser, name='validate_login'),
    url(r'^$', views.ValidateOTP, name='validate_otp'),
    url(r'^saved/', views.HomePage.as_view(), name ='saved'),
    url(r'^employee/$',views.Employee, name='delivery'),
    url(r'^download/$',views.download, name='download'),
    path('accounts/login/', LoginView.as_view(authentication_form=forms.OTPAuthenticationForm), name="login"),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^$', views.index),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from accounts import views
from .views import signup_view, activation_sent_view, activate
from django.contrib.auth import views as auth_views
from django.urls import re_path
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
   url(r'^about/$',views.AboutView.as_view(),name='about'),
   url(r'^contact/$',views.DetailView.as_view(),name='contact'),
   url(r'login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
   url(r'EmployeeLogin/$', auth_views.LoginView.as_view(template_name='blog/employee.html'), name='delivery'),
   url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
   re_path(r'^totp/create/$', views.TOTPCreateView.as_view(), name='totp-create'),
   re_path(r'^totp/login/(?P<token>[0-9]{6})/$', views.TOTPVerifyView.as_view(), name='totp-login'),
   path('post/new/', views.post_new, name='post_new'),
   url(r'^posts/', views.post_detail_view, name='post_list'),
   url(r'^profile/',views.SaveProfile, name='saveprofile'),
   url(r'^post/(?P<pk>\d+)$',views.PostDetailView,name='post_detail'),
   #path('', views.post_list, name='post_list'),
   #path('post/<int:pk>/', views.post_detail, name='post_detail'),
   url(r'post/new/amount',views.calculate_amount_view, name='calculate_amount'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}

{% block content %}

  <div class="about">
    <h1>About this Company</h1>
    <p>Thanks for Checking it out!</p>
  </div>

{% endblock %}

templates/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/activation_sent.html
Activation link sent on your Email address, Please check you mail and click on link to confirm your registration and login into your account. 

templates/admin.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Admin</title>
  </head>
  <body>
    <div class="container">
      <div class="form">
        
        <form method="POST">
          {% csrf_token %}
          <table class="table">
                        <br>
                        <tr>
                            <td><label for="id_username">USERNAME</label></td>
                            <td><input id="id_username" name="username"
                                       type="text" class="form-control"></td>
                        </tr>
                        <tr>
                            <td><label for="id_password">PASSWORD</label></td>
                            <td><input id="id_password" name="password"
                                       type="password" class="form-control"></td>
                        </tr>
                        <br>

                    </table>

                    <button type="submit" class="button button-block" name='login'>Login</button>
                    {% if form.errors %}
                        <p class=" label label-danger">
                            Your username and password didn't match.
                            Please try again.
                        </p>
                    {% endif %}

        </form>
      </div>
    </div>
  </body>
</html>
{% endblock %}

templates/adminpage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title></title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

<link rel="stylesheet" href="/static/css/admin.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css">



  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>
<body class=" dashboard" data-admin-utc-offset="0">

<!-- Container -->
<div id="container">


  <!-- Header -->
  <div id="header">
      <div id="branding">


<link rel="stylesheet" href="/static/css/admin.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css">
<h1 =="" 'head'="">UrbanDelivery Admin</h1>

      </div>


      <div id="user-tools">

              Welcome,
              <strong>gaurav</strong>.



    <!--         <a href="/">View site</a> / -->






              <a href="/administration/password_change/">Change password</a> /

              <a href="/administration/logout/">Log out</a>

      </div>



  </div>
  <!-- END Header -->







  <!-- Content -->
  <div id="content" class="colMS">

      <h1>Welcome to URBAN DELIVERY Portal</h1>

<div id="content-main">



      <div class="app-accounts module">
      <table>
      <caption>
          <a href="/administration/accounts/" class="section" title="Models in the Accounts application">Accounts</a>
      </caption>

          <tbody><tr class="model-deliveryperson">

              <th scope="row"><a href="/administration/accounts/deliveryperson/">Delivery persons</a></th>



              <td><a href="/administration/accounts/deliveryperson/add/" class="addlink">Add</a></td>




              <td><a href="/administration/accounts/deliveryperson/" class="changelink">Change</a></td>


          </tr>

          <tr class="model-post">

              <th scope="row"><a href="/administration/accounts/post/">Posts</a></th>



              <td><a href="/administration/accounts/post/add/" class="addlink">Add</a></td>




              <td><a href="/administration/accounts/post/" class="changelink">Change</a></td>


          </tr>

          <tr class="model-profile">

              <th scope="row"><a href="/administration/accounts/profile/">Profiles</a></th>



              <td><a href="/administration/accounts/profile/add/" class="addlink">Add</a></td>




              <td><a href="/administration/accounts/profile/" class="changelink">Change</a></td>


          </tr>

      </tbody></table>
      </div>

      <div class="app-auth module">
      <table>
      <caption>
          <a href="/administration/auth/" class="section" title="Models in the Authentication and Authorization application">Authentication and Authorization</a>
      </caption>

          <tbody><tr class="model-group">

              <th scope="row"><a href="/administration/auth/group/">Groups</a></th>



              <td><a href="/administration/auth/group/add/" class="addlink">Add</a></td>




              <td><a href="/administration/auth/group/" class="changelink">Change</a></td>


          </tr>

          <tr class="model-user">

              <th scope="row"><a href="/administration/auth/user/">Users</a></th>



              <td><a href="/administration/auth/user/add/" class="addlink">Add</a></td>




              <td><a href="/administration/auth/user/" class="changelink">Change</a></td>


          </tr>

      </tbody></table>
      </div>

      <div class="app-django_twilio module">
      <table>
      <caption>
          <a href="/administration/django_twilio/" class="section" title="Models in the Django_Twilio application">Django_Twilio</a>
      </caption>

          <tbody><tr class="model-caller">

              <th scope="row"><a href="/administration/django_twilio/caller/">Callers</a></th>



              <td><a href="/administration/django_twilio/caller/add/" class="addlink">Add</a></td>




              <td><a href="/administration/django_twilio/caller/" class="changelink">Change</a></td>


          </tr>

          <tr class="model-credential">

              <th scope="row"><a href="/administration/django_twilio/credential/">Credentials</a></th>



              <td><a href="/administration/django_twilio/credential/add/" class="addlink">Add</a></td>




              <td><a href="/administration/django_twilio/credential/" class="changelink">Change</a></td>


          </tr>

      </tbody></table>
      </div>

      <div class="app-otp_totp module">
      <table>
      <caption>
          <a href="/administration/otp_totp/" class="section" title="Models in the Otp_Totp application">Otp_Totp</a>
      </caption>

          <tbody><tr class="model-totpdevice">

              <th scope="row"><a href="/administration/otp_totp/totpdevice/">TOTP devices</a></th>



              <td><a href="/administration/otp_totp/totpdevice/add/" class="addlink">Add</a></td>




              <td><a href="/administration/otp_totp/totpdevice/" class="changelink">Change</a></td>


          </tr>

      </tbody></table>
      </div>


</div>


<div id="content-related">
  <div class="module" id="recent-actions-module">
      <h2>Recent actions</h2>
      <h3>My actions</h3>



          <ul class="actionlist">

          <li class="changelink">

                  <a href="/administration/auth/user/6/change/">Gaurav16</a>

              <br>

                  <span class="mini quiet">User</span>

          </li>

          <li class="changelink">

                  <a href="/administration/auth/user/2/change/">gaurav</a>

              <br>

                  <span class="mini quiet">User</span>

          </li>

          <li class="changelink">

                  Demo Google

              <br>

                  <span class="mini quiet">Socialapp</span>

          </li>

          <li class="changelink">

                  Demo Google

              <br>

                  <span class="mini quiet">Socialapp</span>

          </li>

          <li class="changelink">

                  urbandelivery.com

              <br>

                  <span class="mini quiet">Site</span>

          </li>

          <li class="addlink">

                  Demo Google

              <br>

                  <span class="mini quiet">Socialapp</span>

          </li>

          <li class="changelink">

                  <a href="/administration/accounts/post/12/change/">PIHU</a>

              <br>

                  <span class="mini quiet">Post</span>

          </li>

          <li class="addlink">

                  <a href="/administration/accounts/post/7/change/">PIHU</a>

              <br>

                  <span class="mini quiet">Post</span>

          </li>

          <li class="deletelink">

                  PIHU

              <br>

                  <span class="mini quiet">Post</span>

          </li>

          <li class="deletelink">

                  gaurav

              <br>

                  <span class="mini quiet">Post</span>

          </li>

          </ul>

  </div>
</div>

      <br class="clear">
  </div>
  <!-- END Content -->

  <div id="footer"></div>
</div>
<!-- END Container -->



</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{% block title %}Urban Delivery{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <link rel="stylesheet" href="{% static 'mechit/css/master.css' %}">
    <link rel="stylesheet" href="{% static 'mechit/css/bootstrap.min.css' %}">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>


    </style>
  </head>
  <body>
    <nav class="site-header sticky-top py-1 bg-white">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        {% if user.is_authenticated %}
          {% if  not deliveryperson %}
              <a class='navbar-brand' href='{% url 'home' %}'> Welcome '{{user.username}}'</a>
              <a class='py-2 d-none d-md-inline-block' href="{% url 'accounts:post_new' %}">New Request</a>
              <a class='py-2 d-none d-md-inline-block' href="{% url 'accounts:post_list' %}">Requests</a>
              <table>
                <tr>
                  <td><button type="button" class="btn btn-primary" onclick="location.href='{% url 'accounts:saveprofile' %}';">JOIN US</button></td>
                  <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:logout' %}';">LOGOUT</button></td>
                </tr>
              </table>
          {% else %}
            <a class='navbar-brand' href='{% url 'home' %}'>Welcome '{{user.username}}'</a>
            <table>
              <tr>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:post_list' %}';">CHECK REQUEST</button></td>
                <td><button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:logout' %}';">LOGOUT</button></td>
              </tr>
            </table>
            {% endif %}
        {% else %}
        <a class="navbar-brand" href="{% url 'home' %}" aria-label="Product">URBAN DELIVERY</a>
      <!--    <button type="button" class="btn btn-info" onclick="location.href='{% url 'accounts:delivery' %}';">Delivery Person Login here</button> -->
        <a class="py-2 d-none d-md-inline-block" href="{% url 'signup' %}">
          <i class="fa fa-user" style="font-size:30px"></i>
        </a>

        {% endif %}
      </div>
    </nav>

    </div>
{% block content %}
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}







{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <div class="form">
    <div class="tab-group">
        <div id="tab-signup" onclick="location.href='{% url 'signup' %}';"><h3>SignUp</h3></div>
        <div id="tab-login" onclick="location.href='{% url 'accounts:login' %}';"><h3>Login</h3></div>
    </div>
    <form method="POST" action="{% url 'user_login' %}">
      {% csrf_token %}
      <table class="table">
                    <br>
                    <tr>
                        <td><label for="id_username">USERNAME</label></td>
                        <td><input id="id_username" name="username"
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">PASSWORD</label></td>
                        <td><input id="id_password" name="password"
                                   type="password" class="form-control"></td>
                    </tr>
                    <br>

                </table>

                <button type="submit" class="button button-block" name='login'>Login</button>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}

    </form>
  </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="form">
  <div class="tab-group">
      <div id="tab-signup" onclick="location.href='{% url 'signup' %}';"><h3>SignUp</h3></div>
      <div id="tab-login" onclick="location.href='{% url 'accounts:login' %}';"><h3>Login</h3></div>
  </div>

  <form method="post">
  {% csrf_token %}
  {% for field in form %}
      <p>
        <br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  <button type="submit" class="button button-block">Sign up</button>
  </form>
</div>

{% endblock %}

templates/user.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User</title>
  </head>
  <body>
    <ul class="tab-group">
        <li class="tab active"><a href="{% url 'signup' %}">Sign Up</a></li>
        <li class="tab"><a href="{% url 'accounts:login' %}">Log In</a></li>
      </ul>
  </body>
</html>

templates/validate_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.2.61/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/0.9.0rc1/jspdf.min.js" type="text/javascript">

    </script>
    <script src="{% static 'mechit/js/master.js' %}" type="text/javascript"></script>
  </head>
  <body>
  <div id="content">
    <form action="{% url 'validate_otp' %}" method="post">
      {% csrf_token %}
      <table align='center' border='2'>
        <tr>
          <th>
            <img src="{% static 'qrimages/qrcode.jpg' %}" alt="">
          </th>
        </tr>
        <tr>
          <th>
            <input type="password" required name="otp" placeholder="OTP">
          </th>
        </tr>
        <tr>
          <th>
            <button type="submit" name="button">Check</button>
          </th>
        </tr>
      </table>
    </form>

  </body>
</html>